=== Koriit/PHPCircle/src/PHPCircle/phpcircle.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="PHPCircle" type="PHPCircleType"/>

    <xs:complexType name="ModuleType">
        <xs:sequence>
            <xs:element type="xs:string" name="Name"/>
            <xs:element type="xs:string" name="Namespace"/>
            <xs:element type="xs:string" name="Path"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ModulesType">
        <xs:sequence>
            <xs:element type="ModuleType" name="Module" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ModuleDetectorType">
        <xs:sequence>
            <xs:element type="xs:string" name="Namespace"/>
            <xs:element type="xs:string" name="Path"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="DetectorsType">
        <xs:sequence>
            <xs:element type="ModuleDetectorType" name="ModuleDetector" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PHPCircleType">
        <xs:sequence>
            <xs:element type="ModulesType" name="Modules" minOccurs="0"/>
            <xs:element type="DetectorsType" name="Detectors" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== Koriit/PHPCircle/phpcircle.xml
<?xml version="1.0" encoding="UTF-8"?>
<PHPCircle xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="src/PHPCircle/phpcircle.xsd">
    <Modules>
        <Module>
            <Name>Tokenizer</Name>
            <Namespace>Koriit\PHPCircle\Tokenizer</Namespace>
            <Path>./src/PHPCircle/Tokenizer</Path>
        </Module>

        <Module>
            <Name>Application</Name>
            <Namespace>Koriit\PHPCircle\Application</Namespace>
            <Path>./src/PHPCircle/Application</Path>
        </Module>

        <Module>
            <Name>Graph</Name>
            <Namespace>Koriit\PHPCircle\Graph</Namespace>
            <Path>./src/PHPCircle/Graph</Path>
        </Module>

        <Module>
            <Name>Modules</Name>
            <Namespace>Koriit\PHPCircle\Modules</Namespace>
            <Path>./src/PHPCircle/Modules</Path>
        </Module>

        <Module>
            <Name>Commands</Name>
            <Namespace>Koriit\PHPCircle\Commands</Namespace>
            <Path>./src/PHPCircle/Commands</Path>
        </Module>

        <Module>
            <Name>Config</Name>
            <Namespace>Koriit\PHPCircle\Config</Namespace>
            <Path>./src/PHPCircle/Config</Path>
        </Module>

        <Module>
            <Name>PHPCircleDependencies</Name>
            <Namespace>Koriit\PHPCircle\PHPCircleDependencies</Namespace>
            <Path>./src/PHPCircle/PHPCircleDependencies.php</Path>
        </Module>
    </Modules>
    <!--<ModuleDetectors>-->
    <!--<DirDetector>-->
    <!--<Namespace>Koriit\PHPCircle</Namespace>-->
    <!--<Path>src/PHPCircle</Path>-->
    <!--</DirDetector>-->
    <!--</ModuleDetectors>-->
</PHPCircle>
